# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/mikeolivotto/t1a3" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "artii", "~> 2.1"

gem "tty-prompt", "~> 0.23.1"

gem "tty-font", "~> 0.5.0"

gem "tty-box", "~> 0.7.0"
